title: Sunday Amos # your name (or website title) here
logo: "IMG_20230327_093335.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  <br><br> Hi, i am a skilled data analyst, welcome to my site, please take your time and go through my works. your feedback is highly appreciated 
  
  <a href="https://www.linkedin.com/in/sunday-amos?">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

